---

_You are currently looking at **version 0.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the Jupyter Notebook FAQ course resource._

---

In [91]:
import numpy as np
import pandas as pd

In [92]:
df=pd.read_csv('assets/fraud_data.csv')
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0  1.176563  0.323798  0.536927  1.047002 -0.368652 -0.728586  0.084678   
1  0.681109 -3.934776 -3.801827 -1.147468 -0.735540 -0.501097  1.038865   
2  1.140729  0.453484  0.247010  2.383132  0.343287  0.432804  0.093380   
3 -1.107073 -3.298902 -0.184092 -1.795744  2.137564 -1.684992 -2.015606   
4 -0.314818  0.866839 -0.124577 -0.627638  2.651762  3.428128  0.194637   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0 -0.069246 -0.266389  0.155315  ... -0.109627 -0.341365  0.057845  0.499180   
1 -0.626979 -2.274423  1.527782  ...  0.652202  0.272684 -0.982151  0.165900   
2  0.173310 -0.808999  0.775436  ... -0.003802  0.058556 -0.121177 -0.304215   
3 -0.007181 -0.165760  0.869659  ...  0.130648  0.329445  0.927656 -0.049560   
4  0.670674 -0.442658  0.133499  ... -0.312774 -0.799494 -0.064488  0.953062   

        V25       V26       V27       V28  Amount  Class  
0  0.415211 -0.581949  0.015472  0.018065    4.67      0  
1  0.360251  0.195321 -0.256273  0.056501  912.00      0  
2  0.645893  0.122600 -0.012115 -0.005945    1.00      0  
3 -1.892866 -0.575431  0.266573  0.414184   62.10      0  
4 -0.429550  0.158225  0.076943 -0.015051    2.67      0  

[5 rows x 30 columns]

### Question 1
Import the data from `assets/fraud_data.csv`. What percentage of the observations in the dataset are instances of fraud?

*This function should return a float between 0 and 1.* 

In [93]:
def answer_one():
    df=pd.read_csv('assets/fraud_data.csv')
    return df['Class'].value_counts()[1]/len(df['Class'])
    raise NotImplementedError()


In [94]:
# Use X_train, X_test, y_train, y_test for all of the following questions
from sklearn.model_selection import train_test_split

df = pd.read_csv('assets/fraud_data.csv')

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

### Question 2

Using `X_train`, `X_test`, `y_train`, and `y_test` (as defined above), train a dummy classifier that classifies everything as the majority class of the training data. What is the accuracy of this classifier? What is the recall?

*This function should a return a tuple with two floats, i.e. `(accuracy score, recall score)`.*

In [95]:
def answer_two():
    from sklearn.dummy import DummyClassifier
    from sklearn.metrics import recall_score,accuracy_score
    clf=DummyClassifier().fit(X_train,y_train)
    
    prediction=clf.predict(X_test)
    return accuracy_score(y_test, prediction),recall_score(y_test, prediction)
    
    raise NotImplementedError()

### Question 3

Using X_train, X_test, y_train, y_test (as defined above), train a SVC classifer using the default parameters. What is the accuracy, recall, and precision of this classifier?

*This function should a return a tuple with three floats, i.e. `(accuracy score, recall score, precision score)`.*

In [96]:
def answer_three():
    from sklearn.metrics import recall_score, precision_score,accuracy_score
    from sklearn.svm import SVC
    
    clf=SVC().fit(X_train,y_train)
    prediction=clf.predict(X_test)
    return accuracy_score(y_test, prediction),recall_score(y_test, prediction),precision_score(y_test, prediction)
    raise NotImplementedError()

In [97]:
answer_three()

(0.9900442477876106, 0.35, 0.9333333333333333)

### Question 4

Using the SVC classifier with parameters `{'C': 1e9, 'gamma': 1e-07}`, what is the confusion matrix when using a threshold of -220 on the decision function. Use X_test and y_test.

*This function should return a confusion matrix, a 2x2 numpy array with 4 integers.*

In [125]:
def answer_four():
    from sklearn.metrics import confusion_matrix
    from sklearn.svm import SVC
    clf=SVC(C=1e9,gamma=1e-07).fit(X_train,y_train)
    #prediction=clf.predict(X_test)
    
    #y_decision=clf.decision_function(X_test)
    scores = clf.decision_function(X_test)
    
    y_pred_with_threshold = scores > -220
    confusion=confusion_matrix(y_test, y_pred_with_threshold)
    return confusion
    
    raise NotImplementedError()

In [126]:
answer_four()

(array([[5320,   24],
        [  14,   66]]),
 array([False, False, False, ..., False, False, False]))

### Question 5

Train a logisitic regression classifier with default parameters using X_train and y_train.

For the logisitic regression classifier, create a precision recall curve and a roc curve using y_test and the probability estimates for X_test (probability it is fraud).

Looking at the precision recall curve, what is the recall when the precision is `0.75`?

Looking at the roc curve, what is the true positive rate when the false positive rate is `0.16`?

*This function should return a tuple with two floats, i.e. `(recall, true positive rate)`.*

In [137]:
def answer_five():
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import precision_recall_curve
    from sklearn.metrics import roc_curve

    lr = LogisticRegression().fit(X_train, y_train)
    y_scores_lr = lr.fit(X_train, y_train).decision_function(X_test)
    precision, recall, thresholds = precision_recall_curve(y_test, y_scores_lr)
    fpr, tpr, thresholds2= roc_curve(y_test, y_scores_lr,drop_intermediate=False)
    df=pd.DataFrame(columns=['precision','recall','thresholds'])
    df_r=pd.DataFrame(columns=['fpr','tpr','thresholds2'])
    df['precision']=precision
    df['recall']=recall
    df_r['fpr']=fpr
    df_r['tpr']=tpr
    df_recall=df[df['precision']==.75]
    df_tpr= df_r[(df_r['fpr']<.16) & (df_r['fpr']>.1599)]
    return (df_recall.iloc[0,1],float(df_tpr.iloc[0,1]))
    
    raise NotImplementedError()


In [138]:
answer_five()

(0.825, 0.925)

### Question 6

Perform a grid search over the parameters listed below for a Logisitic Regression classifier, using recall for scoring and the default 3-fold cross validation. (Suggest to use `solver='liblinear'`, more explanation [here](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html))

`'penalty': ['l1', 'l2']`

`'C':[0.01, 0.1, 1, 10]`

From `.cv_results_`, create an array of the mean test scores of each parameter combination. i.e.

|      	| `l1` 	| `l2` 	|
|:----:	|----	|----	|
| **`0.01`** 	|    ?	|   ? 	|
| **`0.1`**  	|    ?	|   ? 	|
| **`1`**    	|    ?	|   ? 	|
| **`10`**   	|    ?	|   ? 	|

<br>

*This function should return a 4 by 2 numpy array with 8 floats.* 

*Note: do not return a DataFrame, just the values denoted by `?` in a numpy array.*

In [139]:
def answer_six():    
    from sklearn.model_selection import GridSearchCV
    from sklearn.linear_model import LogisticRegression
    params={'C':[0.01, 0.1, 1, 10,100],'penalty': ['l1','l2']}
    lr=LogisticRegression(solver='liblinear')
    lrgrid=GridSearchCV(lr,params,scoring='recall',cv=3)
    lrgrid.fit(X_train,y_train)
    return lrgrid.cv_results_.get('mean_test_score').reshape(-1,2)
    raise NotImplementedError()

In [116]:
answer_six()

array([[0.66666667, 0.76086957],
       [0.80072464, 0.80434783],
       [0.8115942 , 0.8115942 ],
       [0.80797101, 0.8115942 ],
       [0.80797101, 0.8115942 ]])

In [119]:
# Use the following function to help visualize results from the grid search
def GridSearch_Heatmap(scores):
    %matplotlib inline
    import seaborn as sns
    import matplotlib.pyplot as plt
    plt.figure()
    sns.heatmap(scores.reshape(4,2), xticklabels=['l1','l2'], yticklabels=[0.01, 0.1, 1, 10])
    plt.yticks(rotation=0);

GridSearch_Heatmap(answer_six())

ValueError: cannot reshape array of size 10 into shape (4,2)

<Figure size 432x288 with 0 Axes>